### ISSUE TITLE
PDF Fragment selectors are no longer defined in RFC 3778

### ISSUE THREAD

**Issue by lrosenthol** [readium/annotations#9]
RFC 3778 was obsoleted by RFC 8118 (https://www.rfc-editor.org/rfc/rfc8118) and then 8118 was obsoleted by ISO 32000-2:2020, Annex O.

**Comment by HadrienGardeur** [comment]
@lrosenthol any particular reason for that?

**Comment by lrosenthol** [comment]
Why was 3778 replaced?  Same reason that many RFCs get replaced - they are out of date and changes have been made.

In this particular area, there are more types of fragment identifiers in the newer specs.

**Comment by HadrienGardeur** [comment]
Got it. Do you think that this draft should be more specific and target a specific subset of these fragment identifiers?

**Comment by lrosenthol** [comment]
Possibly, yes.  There are some that wouldn't make sense in this use case...

**Comment by llemeurfr** [comment]
The reference is in the W3c Web Annotation Data Model https://www.w3.org/TR/annotation-model/#fragment-selector

PDF | http://tools.ietf.org/rfc/rfc3778

We could replace this reference by a new one in our Annotation spec. Who can provide a new URL?

**Comment by lrosenthol** [comment]
Yes, that is my recommendation is to directly reference the updated RFC or ISO 32000.

For the RFC, I put the link in my initial comment.  That should be fine.
